### ISSUE TITLE
 Granularity levels of the 50 Salads dataset

### ISSUE THREAD

**Issue by wlin-at** [Annusha/unsup_temp_embed#2]
Hi, I have a question regarding the granularity levels of the 50 Salads dataset.
In the paper you mentioned you evaluated on two granularity levels: mid-level with 17 subaction classes and eval-level with 9 subaction classes. 
However in the ground truth folder you provided 3 mapping files: `mapping.txt` with 19 classes, `mappingeval.txt` with 12 classes and `mappinghigh.txt` with 5 classes,  all classes including `action_start` and `action_end`.
I wonder which mapping files are used for the results of eval-level (MoF 35.5%) and mid-level (30.2%) given in the paper? Are `action_start` and `action_end` also counted as a subaction class?
Regards

**Comment by Annusha** [comment]
Hi!
I checked code and there is a typo in the paper (sorry for that), the frame-wise accuracy is calculated on all classes in the mapping, thus number of classes is 19 (mid) and 12 (eval). I want to mention that I took classes for mid level from the original paper 'Combining Embedded Accelerometers with Computer Vision for Recognizing Food Preparation Activities'. It is 17 + 2 classes for start and end. For the eval level of granularity there is no references in the original paper but it's more or less described in other papers but when you check different implementations there are no unique version of eval level classes and no mapping from mid to eval levels. Also it can be confusing with the names: eval and mid - in different papers authors call them differently, so check by number of classes they refer to.
It also can be applied for Breakfast dataset: class SIL is included in the evaluation.

Hope it helps.
Best

**Comment by wlin-at** [comment]
Thanks a lot for the explanation! I also had results similar to the ones given in the paper when using the mapping files of 12 classes and 19 classes. 
By the way, do you also plan to release the code of clustering with unknown activity classes which involve bag-of-words using vector quantization?
Regards

**Comment by snorkeldepth** [comment]
> Thanks a lot for the explanation! I also had results similar to the ones given in the paper when using the mapping files of 12 classes and 19 classes.
> By the way, do you also plan to release the code of clustering with unknown activity classes which involve bag-of-words using vector quantization?
> Regards

Would be very interested as there are not that many proposals for this kind/rather similar type of challenge. (Which look promising in real life challenges instead of the usual datasets) ( [https://github.com/Annusha/unsup_temp_embed/blob/master/HOWTO_global.md](https://github.com/Annusha/unsup_temp_embed/blob/master/HOWTO_global.md)  )
Looks pretty promising as a starting point for applied research papers! Lots of implications in medicine / health science. 

Would be super stoked if something is possible here in terms of code release. No need to have it 100% polished and perfect. 

Extremely curious what the code would do with our clinical data. (Not-for-profit academic/clinical research, of course citations etc as usual if we can get something publishable 😃😅)

Thanks a lot in advance already for your really nice paper! 👍

**Comment by Annusha** [comment]
Yeah, it's clearly possible to release the second part of the code. I'll spend time on polishing code and make it reproducible during this month :)

Best,
Anna
